service: slsdadjokebot

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  memorySize: 128
  environment:
    TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
    TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
    TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
    TWITTER_ACCESS_SECRET: ${env:TWITTER_ACCESS_SECRET}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  twitterbot:
    handler: bin/bot
    timeout: 60
    events:
      - schedule:
          name: twitterbot
          enabled: true
          description: run every hour of november
          rate: cron(0 * * 11 ? *)
